### Send GET request with parameter
GET http://localhost:8082/user_etcd/1
Content-Type: application/json

### Send POST request with json body
POST http://localhost:8082/image
Content-Type: application/json

{
  "Name": "UnreadByte",
  "Desc" : "UnreadByte complements ReadByte in implementing the io.ByteScanner interface."
}

### Send POST request with json body failed
POST http://localhost:8082/user_etcd
Content-Type: application/json

{
  "Name": "Santjo",
  "Age": 44,
  "Position": "test"
}